#ifndef VARIABLEDEFINE_H
#define VARIABLEDEFINE_H
#include <QtCore>



//      SERIALENGINE
//int     SERIALENGINE_BAUD_RADE  = 9600;

//QString SERIALENGINE_PORT_NAME  = "ttyACM0";


#endif // VARIABLEDEFINE_H
