
name: linux-builds

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: install qt
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install qt5-default
        sudo apt-get install qtwebengine5-dev
        sudo apt-get install libqt5serialport5-dev
    - name: cmake
      run: cmake .
    - name: make
      run: make
